#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/lqb
#    driverClassName: org.postgresql.Driver
#    username: user
#    password: pw
#  jpa:
#    hibernate:
#      ddl-auto: none
#    database: postgresql
#    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
