spring:
  datasource:
    url: jdbc:postgresql://localhost:2020/springfirst
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
